version: '3.8'

services:
  mongo:
    image: mongo:6.0.13
    container_name: clinic-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: clinic-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/clinic-system
      - JWT_SECRET=your_jwt_secret_key
      - MAIL_USER=youradminemail@gmail.com
      - MAIL_PASS=xxxxxxxxxxxxxx
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: clinic-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
